--- # Dummy config file for testing


  Files: # The files which are plottet together
    - C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\IV_GCD_VPX18592_04_18_GCD_0msWait_14 6 2018_11h54m12s.txt
    #- C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\IV_GCD_VPX18592_04_18_GCD_0msWait_14 6 2018_11h54m12s2.txt
    #- C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\CV_Diode_VC811929_03_16_QD_down_500mV_1kHz_5_7_2019_9h37m40s.txt
    #- C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\CV_Diode_VC811929_17_16_Diode_Down_GuardRingGround_16_7_2018_14h11m57s.txt
    #- C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\CV_Diode_VPX28441_02_15_DiodeLarge_GuardRingGround_11_1_2019_16h44m8s.txt

    #- C:\Users\dbloech\PycharmProjects\Doktorat\PlotScripts\testdata\IVC_VPX28442_2S_20.txt


  Filetype: ASCII # Other options are json

  Output: TestIVCV #Output basename of the plots

  Analysis:
    - IVCV_QTC # The type of analysis, which will be performed

  Poolsize: 4 # Maximum pool size of simultaneous analysis scripts

# Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 3
    measurement_description: 3
    units_line: 3
    data_start: 4

  # Options for the different Analyses scripts
  # These options are entirely up to you and what you need in your analysis
  IVCV_QTC:
      General: # Options common to all plots
          fontsize: {'title': 16, 'labels': 14, 'xticks': 12, 'yticks': 12}
          responsive: False
          width: 750
          height: 400
      #Layout:
      #    cols: 2 # How many columns there are, these must the the names of the methods!!! and a valid parameter

      DoSpecialPlots: # Whether or not to do the SpecialPlot, it may not succeed if not at least one measuremnt has this special plot stated
          - BoxWhisker

      BoxWhiskerOptions:
          shared_axes: False
          box_alpha: 0.3

      temperature[deg]:
          PlotLabel: Temperature
          AdditionalPlots:
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: False
              xlabel: Pad [#]
              ylabel: Temperature [deg]

      humidity[rel%]:
          PlotLabel: Humidity
          AdditionalPlots:
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: False
              xlabel: Pad [#]
              ylabel: Humidity [rel%]

      Current [A]:
          PlotLabel: IV CURVES
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: True
              logx: False
              invert_xaxis: False
              invert_yaxis: false
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              #legend_position: "bottom_right"
              width: 750
              height: 400
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              xlabel: voltage [V]
              ylabel: current [A]
              shared_axes: False # If the axes should be shared with other plots, usually it is False
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: False # If you want to plot the y axis in engineering representation


      Capacity[F]:
          PlotLabel: CV CURVES
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: False
              logx: False
              invert_xaxis: False
              invert_yaxis: False
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              #legend_position: "bottom_right"
              width: 750
              height: 400
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              xlabel: voltage [V]
              ylabel: capacitance [F]
              shared_axes: False

      1C2:
          PlotLabel: CV CURVES - Full depletion
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: False
              logx: False
              invert_xaxis: False
              invert_yaxis: False
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              #legend_position: "bottom_right"
              width: 750
              height: 400
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              xlabel: voltage [V]
              ylabel: 1/c^2 [arb. units]
              shared_axes: False


