---
  Files: # The files which are plotted together
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/FlatBand/2020-07-17T14-48-28_HPK_VPX33234_016_PSS_HM_WW_PQCFlutesRight_GRtoLO_PQC_Flute_1_MOS_capacitor_HV_Source.txt

  Filetype: ASCII # What kind of type is my file, other options are CSV,JSON, customizations

  Output: C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Plots #Output folder path for my plots
  backend: bokeh # Choose the backend for the plotting Warning: Output may change with different backends.

  Save_as: # save the plots in different data formats, if more than one is specified all of them will be plotted
    - png
  
  plot_name: Mos_analysis

  Analysis:
    - MOS_CV # The analysis Plugin over which the data will be run. These plugins must be located in the foler "analysis_scripts"

  Poolsize: 4 # Maximum pool size of simultaneous analysis scripts

  # Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 13
    measurement_description: 14
    units_line: 14
    data_start: 15

  MOS_CV:
    plateau: 0.03    
    General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 24, 'yticks': 24, 'legend': 11}
          responsive: False
          width: 1200
          height: 800
          shared_axes: False
          invert_xaxis: False
          #legend_position: "top_left"
    Derivative:
          do: True
          interpolate: True
          plot: True
    Fit:
          do: True
          interpolate: True
    parameter:
          mos_area: 1.66e-2 #cm²
          phi_m: 4.08 #aluminum work function
          epsilon0: 8.85418e-12 #F/m
          epsilonR: 3.9
          q: 1.60217e-19 #elementary charge in Coulombs
          electronAffinity: 4.05 #eV
          bandGapEnergy: 1.12 #eV
          intrinsicDopingConcentration: 1.45e+10 #cm^-3
          SiliconDoping: 5.0e+12 #cm^-3
          boltzmannConstant: 1.38064e-23 #J/K
          Temperature: 293.15 #kelvin selbst holen !
          n_i_intrinsic_carrier_concentration: 5.415e+9 #cm^-3
          
        
